---
name: Deploy to GitHub Pages
# Controls when the workflow will run
on:
  push:
  pull_request:
# The sequence of runs in this workflow:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: lsb_release -a
      - run: uname -a
      - name: Check out Repository Code
        uses: actions/checkout@v4
        with:
          submodules: true # Fetch submodules
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Set up the environment
        uses: ./.github/actions/setup-emscripten-env
      - run: emcc --version
      - name: Build Project
        run: ./create-images.sh
      - name: Deploy to gh-pages
        uses: crazy-max/ghaction-github-pages@v4
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        with:
          # the output branch mentioned above
          target_branch: gh-pages
          build_dir: ./public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
